version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.name=elasticsearch-rails
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis:5-alpine
    command: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'

  db:
    image: mysql:8.0
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Instabug_App_Chat
      MYSQL_USER: instabug
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  app:
    build: .
    command: bash -c "bundle exec rake db:migrate RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    links:
      - db
      - elasticsearch
      - redis
    environment:
      DB_USER: instabug
      DB_NAME: Instabug_App_Chat
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_URL: redis://redis:6379/1
      ELASTICSEARCH_URL: http://elasticsearch:9200

volumes:
  esdata:
  redis:
